AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway configuration for 中医奶茶养生 App'

Resources:
  ApiGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: ZhongYiNaiChaApi
      Description: API Gateway for 中医奶茶养生 App microservices
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - UserResource
      - RecommendationResource
      - KnowledgeResource
      - RecipeResource
      - OrderResource
      - CommunityResource
      - DataResource
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: 'v1'

  # User Service Resources
  UserResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'users'

  # Recommendation Service Resources
  RecommendationResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'recommendations'

  # Knowledge Service Resources
  KnowledgeResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'knowledge'

  # Recipe Service Resources
  RecipeResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'recipes'

  # Order Service Resources
  OrderResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'orders'

  # Community Service Resources
  CommunityResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'community'

  # Data Service Resources
  DataResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'data'

Outputs:
  ApiEndpoint:
    Description: URL of the API Gateway endpoint
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/v1/'
  ApiId:
    Description: ID of the API Gateway
    Value: !Ref ApiGateway 